[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

# Redirect API requests to our serverless function
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
